dist: trusty
language: c
sudo: required
services:
  - docker

cache:
  directories:
    - .cabal-sandbox/

script:
  - make ci

after_success:
  - make ci_after_success

notifications:
  email:
    on_failure: change
    on_success: never
